[tasks.build]
description = "Build the WASM binary"
run = "wasm-pack build --target web"

[tasks.install-build-deps]
description = "Install build dependencies"
run = "cargo install wasm-pack wasm-opt"

[tools]
rust = { version = "stable", postinstall = "rustup target add wasm32-unknown-unknown" }

[hooks]
postinstall = "mise run install-build-deps"
