[tasks.build]
description = "Build the WASM binary"
run = "wasm-pack build --target web"

[tools]
"aqua:WebAssembly/binaryen" = "120_b"
"aqua:rustwasm/wasm-pack" = "0.13.1"
rust = { version = "1.83.0", postinstall = "rustup target add wasm32-unknown-unknown" }
