name: Build WASM

on:
  push:
    paths:
      - 'src/**'
      - 'build.rs'
      - 'Cargo.toml'
      - 'mise.toml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: jdx/mise-action@v2
      with:
        experimental: true

    - name: Build WASM binary
      run: mise run build

    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-package
        path: pkg/
        retention-days: 7 